### ISSUE TITLE
Issues loading multiple years of CPS data because of variable format mismatch 

### ISSUE THREAD

**Issue by shingtgen** [CenterOnBudget/cbpp-stata-utils#18]
**Describe the bug**
I tried using `load_data` to load March 2019-2021 CPS data but hit an error in the append process because variable `tax_id` changes format over this time period. I got the following error message:

> variable tax_id is long in master but str14 in using data
>     You could specify append's force option to ignore this numeric/string mismatch.  The using variable
>     would then be treated as if it contained numeric missing value.

**To Reproduce**
`load_data cps, years(2019/2021)` 

**Stata version**
MP/17

**Comment by c-zippel** [comment]
TY for flagging! I've been stymied by this too, so I got Arloc's approval to revamp the CPS datasets library so that files (at least back to 2010 or so) are consistently de-stringed, labeled, and include replicate weights.

In the mean time, I think `load_data` could quietly destring the files before appending them.

**Comment by shingtgen** [comment]
That sounds good! Similar issue for ACS and `serialno` too, although I know you've already accounted for that in `load_data`. Would it make sense to update that in the dataset library also? Or do you think it makes sense to handle these differently since one is a variable format issue (CPS) and the other is a change in data format (ACS)?

**Comment by c-zippel** [comment]
The latter, I think. Also, I am hesitant to retroactively modify the existing ACS datasets on the off chance that it breaks someone’s code.
